name: Code Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: install scss lint gem
      run: apt install ruby-dev ; gem install scss_lint

    - name: prepare source files for linting
      run: cp -r ./src/gtk-3.20/ ./gtk320lint && sed -ie 's/%[A-Z0-9_]\+%/123456/g' ./gtk320lint/scss/_global.scss

    - name: scss-lint
      run: scss-lint ./gtk320lint/
